
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileOutputStream;

import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MohamedSharbudeen
 */
public class admin extends javax.swing.JFrame {
Statement stmt=null;
ResultSet rs=null;
    /**
     * Creates new form 
     */
    public admin() {
        initComponents();
    }
    public ArrayList<User> userlist(){
        ArrayList <User> userslist=new ArrayList<>();
        try{
            Connection con = sqlconnect.connectDB();
            String query="select * from foodkart_logindetails";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(query);
            User user;
            while(rs.next())
            {
                user=new User(rs.getString("username"),rs.getString("password"),rs.getString("firstname"),rs.getString("lastname"),rs.getString("email"),rs.getString("mobileno"));
                userslist.add(user);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    return userslist;
    }
    
    public ArrayList<User1> userlist1(){
        ArrayList <User1> userslist1=new ArrayList<>();
        try{
            Connection con = sqlconnect.connectDB();
            String query="select * from foodkart_orderdetails";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(query);
            User1 user1;
            while(rs.next())
            {
                user1=new User1(rs.getString("userid"),rs.getString("name"),rs.getString("date"),rs.getString("orderamount"),rs.getString("mobileno"));
                userslist1.add(user1);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    return userslist1;
    }
    
    public void show_user(){
        ArrayList<User> list=userlist();
        DefaultTableModel model=(DefaultTableModel)display.getModel();
        Object[] row=new Object[6];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getusername();
            row[1]=list.get(i).getpassword();
            row[2]=list.get(i).getfirstname();
            row[3]=list.get(i).getlastname();
            row[4]=list.get(i).getemail();
            row[5]=list.get(i).getmobileno();
            model.addRow(row);
        }
    }
    
        public void show_user1(){
        ArrayList<User1> list1=userlist1();
        DefaultTableModel model=(DefaultTableModel)display.getModel();
        Object[] row=new Object[5];
        for(int i=0;i<list1.size();i++)
        {
            row[0]=list1.get(i).getname();
            row[1]=list1.get(i).getmobileno();
            row[2]=list1.get(i).userid();
            row[3]=list1.get(i).date();
            row[4]=list1.get(i).orderamount();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTable();
        generatexls = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("CLEAR DATABASE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        label1.setText("WELCOME ADMIN");

        jButton1.setText("CUSTOMER DETAILS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ORDER DETAILS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(display);

        generatexls.setText("Generate XLS");
        generatexls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatexlsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(generatexls)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generatexls)
                        .addGap(48, 48, 48))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection con = sqlconnect.connectDB();
        DefaultTableModel model = (DefaultTableModel) display.getModel();
        model.setRowCount(0);
        show_user1();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con = sqlconnect.connectDB();
        DefaultTableModel model = (DefaultTableModel) display.getModel();
        model.setRowCount(0);
        show_user();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void generatexlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatexlsActionPerformed
        // TODO add your handling code here:
        Connection con = sqlconnect.connectDB();
        try{
        Statement statement = con.createStatement();
        ResultSet resultSet = statement.executeQuery("select * from SALES_ANALYSIS");
        
        XSSFWorkbook workbook = new XSSFWorkbook();
        
        XSSFSheet spreadsheet = workbook.createSheet("sales analysis");
        XSSFRow row = spreadsheet.createRow(0);
        XSSFCell cell;
        
        cell = row.createCell(0);
        cell.setCellValue("USERNAME");

        cell = row.createCell(1);
        cell.setCellValue("PIZZA");

        cell = row.createCell(2);
        cell.setCellValue("PIZZAQTY");

        cell = row.createCell(3);
        cell.setCellValue("PIZZASIZE");

        cell = row.createCell(4);
        cell.setCellValue("PASTA");
        
        cell = row.createCell(5);
        cell.setCellValue("PASTAQTY");
        
        cell = row.createCell(6);
        cell.setCellValue("PASTASIZE");
        
        cell = row.createCell(7);
        cell.setCellValue("BEVERAGE");
        
        cell = row.createCell(8);
        cell.setCellValue("BEVERAGEQTY");
        
        cell = row.createCell(9);
        cell.setCellValue("BEVERAGESUGAR");
        
        cell = row.createCell(10);
        cell.setCellValue("ORDERTIME");
        
        cell = row.createCell(11);
        cell.setCellValue("SALES");

        int i=1;
        
        while(resultSet.next()) {
         row = spreadsheet.createRow(i);
         cell = row.createCell(0);
         cell.setCellValue(resultSet.getString("USERNAME"));
         
         cell = row.createCell(1);
         cell.setCellValue(resultSet.getString("PIZZA"));
         
         cell = row.createCell(2);
         cell.setCellValue(resultSet.getInt("PIZZAQTY"));
         
         cell = row.createCell(3);
         cell.setCellValue(resultSet.getString("PIZZASIZE"));
         
         cell = row.createCell(4);
         cell.setCellValue(resultSet.getString("PASTA"));
         
         cell = row.createCell(5);
         cell.setCellValue(resultSet.getInt("PASTAQTY"));
         
         cell = row.createCell(6);
         cell.setCellValue(resultSet.getString("PASTASIZE"));
         
         cell = row.createCell(7);
         cell.setCellValue(resultSet.getString("BEVERAGE"));
         
         cell = row.createCell(8);
         cell.setCellValue(resultSet.getInt("BEVERAGEQTY"));
         
         cell = row.createCell(9);
         cell.setCellValue(resultSet.getString("BEVERAGESUGAR"));
         
         cell = row.createCell(10);
         cell.setCellValue(resultSet.getString("ORDERTIME"));
         
         cell = row.createCell(11);
         cell.setCellValue(resultSet.getString("SALES"));
         
         i++;
      }
        
         FileOutputStream out = new FileOutputStream(
         new File("C:\\Users\\iamsh\\Desktop\\SALESANALYSIS.xlsx"));
        
         workbook.write(out);
         out.close();
      
         JOptionPane.showMessageDialog(null,"Excel Sheet Generated successfully!");
      
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_generatexlsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable display;
    private javax.swing.JButton generatexls;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables

    
}
