/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MohamedSharbudeen
 */
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.*;
import java.time.*;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;  
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
public class cart extends javax.swing.JFrame {

    Connection con=null;
    Statement stmt=null;
    ResultSet rs=null;
    double aa=0.0;
    /**
     * Creates new form cart
     */

    public cart() {
        initComponents();
        (p).setOpaque(false);
        (pt).setOpaque(false);
        (b).setOpaque(false);
        (pizza1).setOpaque(false);
        (pizza2).setOpaque(false);
        (pizza3).setOpaque(false);
        (pizza4).setOpaque(false);
        (pizza5).setOpaque(false);
        (pizza6).setOpaque(false);
        (pizza7).setOpaque(false);
        (pizza8).setOpaque(false);
        (pizza9).setOpaque(false);
        (pasta1).setOpaque(false);
        (pasta2).setOpaque(false);
        (pasta3).setOpaque(false);
        (beverage1).setOpaque(false);
        (beverage2).setOpaque(false);
        (beverage3).setOpaque(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        prevorder = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        buy = new javax.swing.JButton();
        check = new javax.swing.JButton();
        p = new javax.swing.JPanel();
        pizza1 = new javax.swing.JPanel();
        p1image = new javax.swing.JLabel();
        p1name = new javax.swing.JLabel();
        p1quantity = new javax.swing.JSpinner();
        p1size = new javax.swing.JSpinner();
        pizza4 = new javax.swing.JPanel();
        p4image = new javax.swing.JLabel();
        p4name = new javax.swing.JLabel();
        p4quantity = new javax.swing.JSpinner();
        p4size = new javax.swing.JSpinner();
        pizza6 = new javax.swing.JPanel();
        p6image = new javax.swing.JLabel();
        p6name = new javax.swing.JLabel();
        p6quantity = new javax.swing.JSpinner();
        p6size = new javax.swing.JSpinner();
        pizza5 = new javax.swing.JPanel();
        p5image = new javax.swing.JLabel();
        p5name = new javax.swing.JLabel();
        p5quantity = new javax.swing.JSpinner();
        p5size = new javax.swing.JSpinner();
        pizza9 = new javax.swing.JPanel();
        p9image = new javax.swing.JLabel();
        p9name = new javax.swing.JLabel();
        p9quantity = new javax.swing.JSpinner();
        p9size = new javax.swing.JSpinner();
        pizza3 = new javax.swing.JPanel();
        p3image = new javax.swing.JLabel();
        p3name = new javax.swing.JLabel();
        p3quantity = new javax.swing.JSpinner();
        p3size = new javax.swing.JSpinner();
        pizza8 = new javax.swing.JPanel();
        p8image = new javax.swing.JLabel();
        p8name = new javax.swing.JLabel();
        p8quantity = new javax.swing.JSpinner();
        p8size = new javax.swing.JSpinner();
        pizza2 = new javax.swing.JPanel();
        p2name = new javax.swing.JLabel();
        p2image = new javax.swing.JLabel();
        p2quantity = new javax.swing.JSpinner();
        p2size = new javax.swing.JSpinner();
        pizza7 = new javax.swing.JPanel();
        p7image = new javax.swing.JLabel();
        p7name = new javax.swing.JLabel();
        p7quantity = new javax.swing.JSpinner();
        p7size = new javax.swing.JSpinner();
        pt = new javax.swing.JPanel();
        pasta2 = new javax.swing.JPanel();
        pt2image = new javax.swing.JLabel();
        pt2name = new javax.swing.JLabel();
        pt2quantity = new javax.swing.JSpinner();
        pt2size = new javax.swing.JSpinner();
        pasta1 = new javax.swing.JPanel();
        pt1image = new javax.swing.JLabel();
        pt1name = new javax.swing.JLabel();
        pt1quantity = new javax.swing.JSpinner();
        pt1size = new javax.swing.JSpinner();
        pasta3 = new javax.swing.JPanel();
        pt3image = new javax.swing.JLabel();
        pt3name = new javax.swing.JLabel();
        pt3quantity = new javax.swing.JSpinner();
        pt3size = new javax.swing.JSpinner();
        b = new javax.swing.JPanel();
        beverage2 = new javax.swing.JPanel();
        b2image = new javax.swing.JLabel();
        b2name = new javax.swing.JLabel();
        b2quantity = new javax.swing.JSpinner();
        b2rbtn = new javax.swing.JRadioButton();
        beverage1 = new javax.swing.JPanel();
        b1image = new javax.swing.JLabel();
        b1name = new javax.swing.JLabel();
        b1quantity = new javax.swing.JSpinner();
        b1rbtn = new javax.swing.JRadioButton();
        beverage3 = new javax.swing.JPanel();
        b3image = new javax.swing.JLabel();
        b3name = new javax.swing.JLabel();
        b3quantity = new javax.swing.JSpinner();
        b3rbtn = new javax.swing.JRadioButton();
        welcome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        pizza = new javax.swing.JLabel();
        pasta = new javax.swing.JLabel();
        beverage = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 153));

        jPanel1.setLayout(null);

        prevorder.setText("My Previous Orders");
        prevorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevorderActionPerformed(evt);
            }
        });
        jPanel1.add(prevorder);
        prevorder.setBounds(1054, 42, 151, 25);

        logout.setText("Log out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(1280, 42, 75, 25);

        buy.setText("Buy");
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });
        jPanel1.add(buy);
        buy.setBounds(1230, 817, 125, 46);

        check.setText("Check Amount");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        jPanel1.add(check);
        check.setBounds(1053, 819, 146, 42);

        p1image.setIcon(new javax.swing.ImageIcon("C:\\Users\\iamsh\\Downloads\\p1.jpeg")); // NOI18N
        p1image.setPreferredSize(new java.awt.Dimension(150, 150));

        p1name.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        p1name.setForeground(new java.awt.Color(255, 255, 255));
        p1name.setText("The Original: Neapolitan");

        p1quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        p1size.setModel(new javax.swing.SpinnerListModel(new String[] {"Small", "Medium", "Large", "Giant"}));

        javax.swing.GroupLayout pizza1Layout = new javax.swing.GroupLayout(pizza1);
        pizza1.setLayout(pizza1Layout);
        pizza1Layout.setHorizontalGroup(
            pizza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pizza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pizza1Layout.createSequentialGroup()
                        .addComponent(p1quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p1size, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p1name))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pizza1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p1image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pizza1Layout.setVerticalGroup(
            pizza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p1image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p1name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pizza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        p4image.setIcon(new javax.swing.ImageIcon("D:\\foodkart\\2.jpg")); // NOI18N

        p4name.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        p4name.setForeground(new java.awt.Color(255, 255, 255));
        p4name.setText("Chicago Thin Crust");

        p4quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        p4size.setModel(new javax.swing.SpinnerListModel(new String[] {"Small", "Medium", "Large", "Giant"}));

        javax.swing.GroupLayout pizza4Layout = new javax.swing.GroupLayout(pizza4);
        pizza4.setLayout(pizza4Layout);
        pizza4Layout.setHorizontalGroup(
            pizza4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pizza4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p4name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pizza4Layout.createSequentialGroup()
                        .addGroup(pizza4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pizza4Layout.createSequentialGroup()
                                .addComponent(p4quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p4size, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(p4image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        pizza4Layout.setVerticalGroup(
            pizza4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p4image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p4name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pizza4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p4size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        p6image.setIcon(new javax.swing.ImageIcon("D:\\foodkart\\9.jpg")); // NOI18N

        p6name.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        p6name.setForeground(new java.awt.Color(255, 255, 255));
        p6name.setText("New England Greek");

        p6quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        p6size.setModel(new javax.swing.SpinnerListModel(new String[] {"Small", "Medium", "Large", "Giant"}));

        javax.swing.GroupLayout pizza6Layout = new javax.swing.GroupLayout(pizza6);
        pizza6.setLayout(pizza6Layout);
        pizza6Layout.setHorizontalGroup(
            pizza6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pizza6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pizza6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(p6image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p6name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pizza6Layout.createSequentialGroup()
                        .addComponent(p6quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p6size, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pizza6Layout.setVerticalGroup(
            pizza6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p6image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p6name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pizza6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p6quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p6size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        p5image.setIcon(new javax.swing.ImageIcon("D:\\foodkart\\img_6941_6018.JPEG")); // NOI18N

        p5name.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        p5name.setForeground(new java.awt.Color(255, 255, 255));
        p5name.setText("Detroit Style");

        p5quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        p5size.setModel(new javax.swing.SpinnerListModel(new String[] {"Small", "Medium", "Large", "Giant"}));

        javax.swing.GroupLayout pizza5Layout = new javax.swing.GroupLayout(pizza5);
        pizza5.setLayout(pizza5Layout);
        pizza5Layout.setHorizontalGroup(
            pizza5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pizza5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pizza5Layout.createSequentialGroup()
                        .addComponent(p5quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p5size))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pizza5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(pizza5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p5name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p5image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pizza5Layout.setVerticalGroup(
            pizza5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pizza5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p5image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pizza5Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(p5name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pizza5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p5quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p5size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        p9image.setIcon(new javax.swing.ImageIcon("D:\\foodkart\\3.jpg")); // NOI18N

        p9name.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        p9name.setForeground(new java.awt.Color(255, 255, 255));
        p9name.setText("Tomato Pie New Jersey style");

        p9quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        p9size.setModel(new javax.swing.SpinnerListModel(new String[] {"Small", "Medium", "Large", "Giant"}));

        javax.swing.GroupLayout pizza9Layout = new javax.swing.GroupLayout(pizza9);
        pizza9.setLayout(pizza9Layout);
        pizza9Layout.setHorizontalGroup(
            pizza9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pizza9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p9image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p9name)
                    .addGroup(pizza9Layout.createSequentialGroup()
                        .addComponent(p9quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p9size, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(212, 212, 212))
        );
        pizza9Layout.setVerticalGroup(
            pizza9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p9image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p9name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pizza9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p9quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p9size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p3image.setIcon(new javax.swing.ImageIcon("D:\\foodkart\\Margherita-pizza-256x256.jpg")); // NOI18N

        p3name.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        p3name.setForeground(new java.awt.Color(255, 255, 255));
        p3name.setText("Chicago Deep Dish");

        p3quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        p3size.setModel(new javax.swing.SpinnerListModel(new String[] {"Small", "Medium", "Large", "Giant"}));

        javax.swing.GroupLayout pizza3Layout = new javax.swing.GroupLayout(pizza3);
        pizza3.setLayout(pizza3Layout);
        pizza3Layout.setHorizontalGroup(
            pizza3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pizza3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p3image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pizza3Layout.createSequentialGroup()
                        .addComponent(p3quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p3size)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pizza3Layout.setVerticalGroup(
            pizza3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p3image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p3name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pizza3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p8image.setIcon(new javax.swing.ImageIcon("D:\\foodkart\\7.jpg")); // NOI18N

        p8name.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        p8name.setForeground(new java.awt.Color(255, 255, 255));
        p8name.setText("St. Louis Style");

        p8quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        p8size.setModel(new javax.swing.SpinnerListModel(new String[] {"Small", "Medium", "Large", "Giant"}));

        javax.swing.GroupLayout pizza8Layout = new javax.swing.GroupLayout(pizza8);
        pizza8.setLayout(pizza8Layout);
        pizza8Layout.setHorizontalGroup(
            pizza8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pizza8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p8image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p8name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pizza8Layout.createSequentialGroup()
                        .addComponent(p8quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p8size, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pizza8Layout.setVerticalGroup(
            pizza8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pizza8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pizza8Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(p8name, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pizza8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p8quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p8size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(p8image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p2name.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        p2name.setForeground(new java.awt.Color(255, 255, 255));
        p2name.setText("California Style");

        p2image.setIcon(new javax.swing.ImageIcon("D:\\foodkart\\3.jpg")); // NOI18N

        p2quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        p2size.setModel(new javax.swing.SpinnerListModel(new String[] {"Small", "Medium", "Large", "Giant"}));

        javax.swing.GroupLayout pizza2Layout = new javax.swing.GroupLayout(pizza2);
        pizza2.setLayout(pizza2Layout);
        pizza2Layout.setHorizontalGroup(
            pizza2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pizza2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2name, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pizza2Layout.createSequentialGroup()
                        .addComponent(p2quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p2size, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p2image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pizza2Layout.setVerticalGroup(
            pizza2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p2image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p2name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pizza2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p7image.setIcon(new javax.swing.ImageIcon("D:\\foodkart\\8.jpg")); // NOI18N

        p7name.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        p7name.setForeground(new java.awt.Color(255, 255, 255));
        p7name.setText("New York Thin Crust");

        p7quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        p7size.setModel(new javax.swing.SpinnerListModel(new String[] {"Small", "Medium", "Large", "Giant"}));

        javax.swing.GroupLayout pizza7Layout = new javax.swing.GroupLayout(pizza7);
        pizza7.setLayout(pizza7Layout);
        pizza7Layout.setHorizontalGroup(
            pizza7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pizza7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pizza7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(p7name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p7image, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pizza7Layout.createSequentialGroup()
                        .addComponent(p7quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p7size, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pizza7Layout.setVerticalGroup(
            pizza7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizza7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p7image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p7name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pizza7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p7quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p7size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pLayout = new javax.swing.GroupLayout(p);
        p.setLayout(pLayout);
        pLayout.setHorizontalGroup(
            pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLayout.createSequentialGroup()
                        .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pLayout.createSequentialGroup()
                                .addComponent(pizza4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pizza5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pLayout.createSequentialGroup()
                                .addComponent(pizza7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pizza8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pizza6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pizza9, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pLayout.createSequentialGroup()
                        .addComponent(pizza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pizza2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pizza3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pLayout.setVerticalGroup(
            pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pizza3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pizza1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pizza2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pizza4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pizza5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pizza6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pizza8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pizza7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pizza9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(p);
        p.setBounds(20, 120, 591, 770);

        pt2image.setIcon(new javax.swing.ImageIcon("D:\\foodkart\\k.jpg")); // NOI18N

        pt2name.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        pt2name.setForeground(new java.awt.Color(255, 255, 255));
        pt2name.setText("Pasta primavera");

        pt2quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        pt2size.setModel(new javax.swing.SpinnerListModel(new String[] {"Less cheese", "Moderate cheese", "cheese burst"}));

        javax.swing.GroupLayout pasta2Layout = new javax.swing.GroupLayout(pasta2);
        pasta2.setLayout(pasta2Layout);
        pasta2Layout.setHorizontalGroup(
            pasta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasta2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pasta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pasta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pt2image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pt2name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pasta2Layout.createSequentialGroup()
                        .addComponent(pt2quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pt2size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pasta2Layout.setVerticalGroup(
            pasta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasta2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pt2image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pt2name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pasta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pt2quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pt2size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pt1image.setIcon(new javax.swing.ImageIcon("D:\\foodkart\\j.jpg")); // NOI18N

        pt1name.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        pt1name.setForeground(new java.awt.Color(255, 255, 255));
        pt1name.setText("Classic italian lasagna");

        pt1quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        pt1size.setModel(new javax.swing.SpinnerListModel(new String[] {"Less cheese", "Moderate cheese", "cheese burst"}));

        javax.swing.GroupLayout pasta1Layout = new javax.swing.GroupLayout(pasta1);
        pasta1.setLayout(pasta1Layout);
        pasta1Layout.setHorizontalGroup(
            pasta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasta1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pasta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pt1image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pt1name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pasta1Layout.createSequentialGroup()
                        .addComponent(pt1quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pt1size)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pasta1Layout.setVerticalGroup(
            pasta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pt1image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pt1name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pasta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pt1quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pt1size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pt3image.setIcon(new javax.swing.ImageIcon("D:\\foodkart\\l.jpg")); // NOI18N

        pt3name.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        pt3name.setForeground(new java.awt.Color(255, 255, 255));
        pt3name.setText("Macaroni and cheese");

        pt3quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        pt3size.setModel(new javax.swing.SpinnerListModel(new String[] {"Less cheese", "Moderate cheese", "cheese burst"}));

        javax.swing.GroupLayout pasta3Layout = new javax.swing.GroupLayout(pasta3);
        pasta3.setLayout(pasta3Layout);
        pasta3Layout.setHorizontalGroup(
            pasta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasta3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pasta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pt3image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pt3name)
                    .addGroup(pasta3Layout.createSequentialGroup()
                        .addComponent(pt3quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pt3size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(203, 203, 203))
        );
        pasta3Layout.setVerticalGroup(
            pasta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasta3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pt3image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pt3name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pasta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pt3quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pt3size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ptLayout = new javax.swing.GroupLayout(pt);
        pt.setLayout(ptLayout);
        ptLayout.setHorizontalGroup(
            ptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pasta3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pasta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ptLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pasta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ptLayout.setVerticalGroup(
            ptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pasta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pasta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pasta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(pt);
        pt.setBounds(610, 120, 223, 770);

        b2image.setIcon(new javax.swing.ImageIcon("D:\\foodkart\\c.jpg")); // NOI18N

        b2name.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        b2name.setForeground(new java.awt.Color(255, 255, 255));
        b2name.setText("Avacado mix");

        b2quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        b2rbtn.setText("Sugar free");

        javax.swing.GroupLayout beverage2Layout = new javax.swing.GroupLayout(beverage2);
        beverage2.setLayout(beverage2Layout);
        beverage2Layout.setHorizontalGroup(
            beverage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beverage2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(beverage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2name, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, beverage2Layout.createSequentialGroup()
                        .addComponent(b2quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b2rbtn)))
                .addContainerGap())
        );
        beverage2Layout.setVerticalGroup(
            beverage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beverage2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(b2image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b2name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(beverage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2rbtn)
                    .addComponent(b2quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        b1image.setIcon(new javax.swing.ImageIcon("D:\\foodkart\\a.png")); // NOI18N

        b1name.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        b1name.setForeground(new java.awt.Color(255, 255, 255));
        b1name.setText("Foodkart coffee");

        b1quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        b1rbtn.setText("Sugar free");
        b1rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1rbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout beverage1Layout = new javax.swing.GroupLayout(beverage1);
        beverage1.setLayout(beverage1Layout);
        beverage1Layout.setHorizontalGroup(
            beverage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beverage1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(beverage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(beverage1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(b1name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(beverage1Layout.createSequentialGroup()
                        .addComponent(b1quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b1rbtn))
                    .addGroup(beverage1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(b1image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        beverage1Layout.setVerticalGroup(
            beverage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beverage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b1image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b1name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(beverage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b1rbtn)
                    .addComponent(b1quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        b3image.setIcon(new javax.swing.ImageIcon("D:\\foodkart\\b.jpg")); // NOI18N

        b3name.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        b3name.setForeground(new java.awt.Color(255, 255, 255));
        b3name.setText("Cinnamon ginger");

        b3quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        b3rbtn.setText("Sugar free");
        b3rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3rbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout beverage3Layout = new javax.swing.GroupLayout(beverage3);
        beverage3.setLayout(beverage3Layout);
        beverage3Layout.setHorizontalGroup(
            beverage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beverage3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(beverage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(beverage3Layout.createSequentialGroup()
                        .addComponent(b3quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3rbtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, beverage3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(beverage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b3image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        beverage3Layout.setVerticalGroup(
            beverage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beverage3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(b3image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b3name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(beverage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3rbtn))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout bLayout = new javax.swing.GroupLayout(b);
        b.setLayout(bLayout);
        bLayout.setHorizontalGroup(
            bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bLayout.createSequentialGroup()
                .addGroup(bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beverage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bLayout.createSequentialGroup()
                        .addGroup(bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(beverage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(beverage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bLayout.setVerticalGroup(
            bLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(beverage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(beverage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(beverage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(b);
        b.setBounds(831, 116, 203, 770);

        welcome.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("Welcome !");
        jPanel1.add(welcome);
        welcome.setBounds(28, 22, 75, 20);

        textarea.setColumns(20);
        textarea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        textarea.setRows(5);
        jScrollPane1.setViewportView(textarea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(1054, 74, 301, 741);

        pizza.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        pizza.setForeground(new java.awt.Color(255, 255, 255));
        pizza.setText("PIZZA");
        jPanel1.add(pizza);
        pizza.setBounds(310, 90, 50, 20);

        pasta.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        pasta.setForeground(new java.awt.Color(255, 255, 255));
        pasta.setText("PASTA");
        jPanel1.add(pasta);
        pasta.setBounds(700, 90, 45, 20);

        beverage.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        beverage.setForeground(new java.awt.Color(255, 255, 255));
        beverage.setText("BEVERAGE");
        jPanel1.add(beverage);
        beverage.setBounds(910, 90, 73, 20);

        username.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(username);
        username.setBounds(100, 20, 120, 20);

        background.setIcon(new javax.swing.ImageIcon("D:\\foodkart\\window-drop-rain-light-blurry.jpg")); // NOI18N
        jPanel1.add(background);
        background.setBounds(-10, 0, 1390, 970);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1379, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1rbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1rbtnActionPerformed

    private void b3rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3rbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3rbtnActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
        
        //quantity of each pizza
        int p1=Integer.parseInt(p1quantity.getValue().toString());
        int p2=Integer.parseInt(p2quantity.getValue().toString());
        int p3=Integer.parseInt(p3quantity.getValue().toString());
        int p4=Integer.parseInt(p4quantity.getValue().toString());
        int p5=Integer.parseInt(p5quantity.getValue().toString());
        int p6=Integer.parseInt(p6quantity.getValue().toString());
        int p7=Integer.parseInt(p7quantity.getValue().toString());
        int p8=Integer.parseInt(p8quantity.getValue().toString());
        int p9=Integer.parseInt(p9quantity.getValue().toString());
        
        
        //quantity of each pasta
        int pt1=Integer.parseInt(pt1quantity.getValue().toString());
        int pt2=Integer.parseInt(pt2quantity.getValue().toString());
        int pt3=Integer.parseInt(pt3quantity.getValue().toString());
        
        
        //quantity of each beverage
        int b1=Integer.parseInt(b1quantity.getValue().toString());
        int b2=Integer.parseInt(b2quantity.getValue().toString());
        int b3=Integer.parseInt(b3quantity.getValue().toString());
        
        //size of each pizza
        String s1=p1size.getValue().toString();
        String s2=p2size.getValue().toString();
        String s3=p3size.getValue().toString();
        String s4=p4size.getValue().toString();
        String s5=p5size.getValue().toString();
        String s6=p6size.getValue().toString();
        String s7=p7size.getValue().toString();
        String s8=p8size.getValue().toString();
        String s9=p9size.getValue().toString();
        
        //size of each pasta
        String pt1s=pt1size.getValue().toString();
        String pt2s=pt2size.getValue().toString();
        String pt3s=pt3size.getValue().toString();

        
        //prize
        double pp[]={250.99,264.99,199.00,225.50,211.99,200.00,156,00,173.00,210.50};
        double ptp[]={150.00,200.50,120.00};
        double dd[]={100.50,120.50,125.99};
        double total =0;
        double tax=0;
        
        String pname[]={"The Original: Neapolitan","California Style","Chicago Deep Dish","Chicago Thin Crust","Detroit Style","New England Greek","New York Thin Crust","St. Louis Style","Tomato Pie New Jersey style"};
        String ptname[]={"Classic italian lasagna","Pasta primavera","Macaroni and cheese"};
        String dname[]={"Foodkart coffee","Avacado mix","Cinnamon ginger"};
        int parrq[]={p1,p2,p3,p4,p5,p6,p7,p8,p9};
        String parrs[]={s1,s2,s3,s4,s5,s6,s7,s8,s9};
        int ptarrq[]={pt1,pt2,pt3};
        String ptarrs[]={pt1s,pt2s,pt3s};
        int darr[]={b1,b2,b3};
        double sum=0;
        
        String str="";
        str=str+"Your Order:\n------------------------------\nitem\tquantity\tsize\tprice\t\n";
        
        for(int i=0;i<parrq.length;i++)
        {
            if(parrq[i]>0)
            {
                double s=1.0;
                if("Small".equals(parrs[i]))
                {
                    s=0.80;
                }
                if("Large".equals(parrs[i]))
                {
                    s=1.50;
                }
                if("Giant".equals(parrs[i]))
                {
                    s=2.0;
                }
                double amt=Math.round(parrq[i]*pp[i]*s * 100.0) / 100.0;
                
                String a=Double.toString(amt);
                String b=Integer.toString(parrq[i]);
                str=str+pname[i]+"\t"+b+"\t"+parrs[i]+"\t"+a+"\n";
                sum=sum+amt;
                //db entry
            }
        }
        str=str+"\n";
        for(int i=0;i<ptarrq.length;i++)
        {
            if(ptarrq[i]>0)
            {
                double pt=Math.round(ptarrq[i]*ptp[i]*100)/100.0;
                str=str+ptname[i]+"\t"+ptarrq[i]+"\t"+ptarrs[i]+"\t"+pt+"\n";
                sum=sum+pt;
            }
        }
        str=str+"\n";
        for(int i=0;i<darr.length;i++)
        {
            if(darr[i]>0)
            {
                double d=Math.round(darr[i]*dd[i] * 100.0) / 100.0;
                
                str=str+dname[i]+"\t"+darr[i]+"\t"+"\t"+"\t"+d+"\n";
                sum=sum+d;
            }
        }
        str=str+"------------------------------\n";
        
        total =Math.round(sum * 100.0) / 100.0;;
        tax=Math.round(sum*0.10 * 100.0) / 100.0;
        aa=Math.round((total+tax) * 100.0) / 100.0;
        str=str+"\n";
        str=str+"\tamount=\t"+total+" rs\n";
        str=str+"\ttax=\t"+tax+" rs\n";
        str=str+"\tTotal=\t"+aa+" rs\n";
        str=str+"\n\tHave a nice day";
        
        
        
        textarea.setText(str);
        
       
    }//GEN-LAST:event_checkActionPerformed

    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
        // TODO add your handling code here:
        try{

        con = sqlconnect.connectDB();
        if(aa==0)
        {
            JOptionPane.showMessageDialog(null,"Select any item to Continue! or Check your amount!");
        }
        else
        {
        String fname="";
        long mobile=0;
        String amt=Double.toString(aa);
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
        LocalDateTime now = LocalDateTime.now();  
        String date=dtf.format(now);
        String usrname=username.getText();
        
        String query="Select firstname,mobileno from FOODKART_LOGINDETAILS WHERE USERNAME='"+usrname+"'";
        stmt=con.createStatement();
        rs=stmt.executeQuery(query);
        while(rs.next())
        {
            fname=rs.getString("firstname");
            mobile=rs.getLong("mobileno");
        }
        //datas
        String pizzanames[]=new String[9];
        int pizzaquantity[]=new int[9];
        String pizzasize[]=new String[9];
        int x=0;
        if((Integer)p1quantity.getValue()>0)
        {
            pizzanames[x]=p1name.getText();
            pizzaquantity[x]=(Integer)p1quantity.getValue();
            pizzasize[x]=p1size.getValue().toString();
            x++;
        }
        if((Integer)p2quantity.getValue()>0)
        {
            pizzanames[x]=p2name.getText();
            pizzaquantity[x]=(Integer)p2quantity.getValue();
            pizzasize[x]=p2size.getValue().toString();
            x++;
        }
        if((Integer)p3quantity.getValue()>0)
        {
            pizzanames[x]=p3name.getText();
            pizzaquantity[x]=(Integer)p3quantity.getValue();
            pizzasize[x]=p3size.getValue().toString();
            x++;
        }
        if((Integer)p4quantity.getValue()>0)
        {
            pizzanames[x]=p4name.getText();
            pizzaquantity[x]=(Integer)p4quantity.getValue();
            pizzasize[x]=p4size.getValue().toString();
            x++;
        }
        if((Integer)p5quantity.getValue()>0)
        {
            pizzanames[x]=p5name.getText();
            pizzaquantity[x]=(Integer)p5quantity.getValue();
            pizzasize[x]=p5size.getValue().toString();
            x++;
        }
        if((Integer)p6quantity.getValue()>0)
        {
            pizzanames[x]=p6name.getText();
            pizzaquantity[x]=(Integer)p6quantity.getValue();
            pizzasize[x]=p6size.getValue().toString();
            x++;
        }
        if((Integer)p7quantity.getValue()>0)
        {
            pizzanames[x]=p7name.getText();
            pizzaquantity[x]=(Integer)p7quantity.getValue();
            pizzasize[x]=p7size.getValue().toString();
            x++;
        }
        if((Integer)p8quantity.getValue()>0)
        {
            pizzanames[x]=p8name.getText();
            pizzaquantity[x]=(Integer)p8quantity.getValue();
            pizzasize[x]=p8size.getValue().toString();
            x++;
        }
        if((Integer)p9quantity.getValue()>0)
        {
            pizzanames[x]=p9name.getText();
            pizzaquantity[x]=(Integer)p9quantity.getValue();
            pizzasize[x]=p9size.getValue().toString();
            x++;
        }
        String istatement="Insert into SALES_ANALYSIS values(?,?,?,?,?,?,?,?,?,?,?,?)";
        PreparedStatement pstmt=con.prepareStatement(istatement);
        String emptystring="";
        int emptyint=0;
        for(int i=0;i<x;i++)
        {
            pstmt.setString(1, usrname);
            pstmt.setString(2, pizzanames[i]);
            pstmt.setInt(3, pizzaquantity[i]);
            pstmt.setString(4, pizzasize[i]);
            pstmt.setString(5, null);
            pstmt.setInt(6, emptyint);
            pstmt.setString(7, null);
            pstmt.setString(8, null);
            pstmt.setInt(9, emptyint);
            pstmt.setString(10, null);
            pstmt.setString(11,date);
            pstmt.setDouble(12,aa);
            pstmt.executeUpdate();
        }
        String pastanames[]=new String[3];
        int pastaquantity[]=new int[3];
        String pastasize[]=new String[3];
        x=0;
        if((Integer)pt1quantity.getValue()>0)
        {
            pastanames[x]=pt1name.getText();
            pastaquantity[x]=(Integer)pt1quantity.getValue();
            pastasize[x]=pt1size.getValue().toString();
            x++;
        }
        if((Integer)pt2quantity.getValue()>0)
        {
            pastanames[x]=pt2name.getText();
            pastaquantity[x]=(Integer)pt2quantity.getValue();
            pastasize[x]=pt2size.getValue().toString();
            x++;
        }
        if((Integer)pt3quantity.getValue()>0)
        {
            pastanames[x]=pt3name.getText();
            pastaquantity[x]=(Integer)pt3quantity.getValue();
            pastasize[x]=pt3size.getValue().toString();
            x++;
        }
        for(int i=0;i<x;i++)
        {
            pstmt.setString(1, usrname);
            pstmt.setString(2, null);
            pstmt.setInt(3, emptyint);
            pstmt.setString(4, null);
            pstmt.setString(5, pastanames[i]);
            pstmt.setInt(6, pastaquantity[i]);
            pstmt.setString(7, pastasize[i]);
            pstmt.setString(8, null);
            pstmt.setInt(9, emptyint);
            pstmt.setString(10, null);
            pstmt.setString(11,date);
            pstmt.setDouble(12,aa);
            pstmt.executeUpdate();
        }
        
        String beveragenames[]=new String[3];
        int beveragequantity[]=new int[3];
        String sugarornot[]=new String[3];
        x=0;
        if((Integer)b1quantity.getValue()>0)
        {
            beveragenames[x]=b1name.getText();
            beveragequantity[x]=(Integer)b1quantity.getValue();
            if(b1rbtn.isSelected())
            {
            sugarornot[x]="yes";
            }
            else
            {
                sugarornot[x]="no";
            }

            x++;
        }
        if((Integer)b2quantity.getValue()>0)
        {
            beveragenames[x]=b2name.getText();
            beveragequantity[x]=(Integer)b2quantity.getValue();
            if(b2rbtn.isSelected())
            {
            sugarornot[x]="yes";
            }
            else
            {
                sugarornot[x]="no";
            }

            x++;
        }
        if((Integer)b3quantity.getValue()>0)
        {
            beveragenames[x]=b3name.getText();
            beveragequantity[x]=(Integer)b3quantity.getValue();
            if(b3rbtn.isSelected())
            {
            sugarornot[x]="no";
            }
            else
            {
                sugarornot[x]="yes";
            }

            x++;
        }
        for(int i=0;i<x;i++)
        {
            pstmt.setString(1, usrname);
            pstmt.setString(2, null);
            pstmt.setInt(3, emptyint);
            pstmt.setString(4, null);
            pstmt.setString(5, null);
            pstmt.setInt(6, emptyint);
            pstmt.setString(7, null);
            pstmt.setString(8, beveragenames[i]);
            pstmt.setInt(9, beveragequantity[i]);
            pstmt.setString(10, sugarornot[i]);
            pstmt.setString(11,date);
            pstmt.setDouble(12,aa);
            pstmt.executeUpdate();
        }
        
        
        String insert="Insert into FOODKART_ORDERDETAILS values (?,?,?,?,?)";
        PreparedStatement ps=con.prepareStatement(insert);
        ps.setString(1, fname);
        ps.setLong(2,mobile);
        ps.setDouble(3, aa);
        ps.setString(4, date);
        ps.setString(5, usrname);
        
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Your Request is Processed Sucessfully!");
        }
        
        
        
           } catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_buyActionPerformed

    private void prevorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevorderActionPerformed
        // TODO add your handling code here:
        try{
            con = sqlconnect.connectDB();
            String usrname=username.getText();
            String print="date\t\tamount\n--------------------------------------------------------------\n";
            String prev="Select date,orderamount from FOODKART_ORDERDETAILS WHERE USERID='"+usrname+"'";
            stmt=con.createStatement();
            rs=stmt.executeQuery(prev);
            
            while(rs.next())
            {
                String da=rs.getString("date");
                String am=Integer.toString(rs.getInt("orderamount"));
                print=print+da+"\t\t"+am+"\n";
            }
            textarea.setText(print);
        }
        catch(HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        } catch (SQLException ex) {
            Logger.getLogger(cart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_prevorderActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        login lgn=new login();
        cart crt=new cart();
        
        lgn.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new cart().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel b;
    private javax.swing.JLabel b1image;
    private javax.swing.JLabel b1name;
    private javax.swing.JSpinner b1quantity;
    private javax.swing.JRadioButton b1rbtn;
    private javax.swing.JLabel b2image;
    private javax.swing.JLabel b2name;
    private javax.swing.JSpinner b2quantity;
    private javax.swing.JRadioButton b2rbtn;
    private javax.swing.JLabel b3image;
    private javax.swing.JLabel b3name;
    private javax.swing.JSpinner b3quantity;
    private javax.swing.JRadioButton b3rbtn;
    private javax.swing.JLabel background;
    private javax.swing.JLabel beverage;
    private javax.swing.JPanel beverage1;
    private javax.swing.JPanel beverage2;
    private javax.swing.JPanel beverage3;
    private javax.swing.JButton buy;
    private javax.swing.JButton check;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JPanel p;
    private javax.swing.JLabel p1image;
    private javax.swing.JLabel p1name;
    private javax.swing.JSpinner p1quantity;
    private javax.swing.JSpinner p1size;
    private javax.swing.JLabel p2image;
    private javax.swing.JLabel p2name;
    private javax.swing.JSpinner p2quantity;
    private javax.swing.JSpinner p2size;
    private javax.swing.JLabel p3image;
    private javax.swing.JLabel p3name;
    private javax.swing.JSpinner p3quantity;
    private javax.swing.JSpinner p3size;
    private javax.swing.JLabel p4image;
    private javax.swing.JLabel p4name;
    private javax.swing.JSpinner p4quantity;
    private javax.swing.JSpinner p4size;
    private javax.swing.JLabel p5image;
    private javax.swing.JLabel p5name;
    private javax.swing.JSpinner p5quantity;
    private javax.swing.JSpinner p5size;
    private javax.swing.JLabel p6image;
    private javax.swing.JLabel p6name;
    private javax.swing.JSpinner p6quantity;
    private javax.swing.JSpinner p6size;
    private javax.swing.JLabel p7image;
    private javax.swing.JLabel p7name;
    private javax.swing.JSpinner p7quantity;
    private javax.swing.JSpinner p7size;
    private javax.swing.JLabel p8image;
    private javax.swing.JLabel p8name;
    private javax.swing.JSpinner p8quantity;
    private javax.swing.JSpinner p8size;
    private javax.swing.JLabel p9image;
    private javax.swing.JLabel p9name;
    private javax.swing.JSpinner p9quantity;
    private javax.swing.JSpinner p9size;
    private javax.swing.JLabel pasta;
    private javax.swing.JPanel pasta1;
    private javax.swing.JPanel pasta2;
    private javax.swing.JPanel pasta3;
    private javax.swing.JLabel pizza;
    private javax.swing.JPanel pizza1;
    private javax.swing.JPanel pizza2;
    private javax.swing.JPanel pizza3;
    private javax.swing.JPanel pizza4;
    private javax.swing.JPanel pizza5;
    private javax.swing.JPanel pizza6;
    private javax.swing.JPanel pizza7;
    private javax.swing.JPanel pizza8;
    private javax.swing.JPanel pizza9;
    private javax.swing.JButton prevorder;
    private javax.swing.JPanel pt;
    private javax.swing.JLabel pt1image;
    private javax.swing.JLabel pt1name;
    private javax.swing.JSpinner pt1quantity;
    private javax.swing.JSpinner pt1size;
    private javax.swing.JLabel pt2image;
    private javax.swing.JLabel pt2name;
    private javax.swing.JSpinner pt2quantity;
    private javax.swing.JSpinner pt2size;
    private javax.swing.JLabel pt3image;
    private javax.swing.JLabel pt3name;
    private javax.swing.JSpinner pt3quantity;
    private javax.swing.JSpinner pt3size;
    private javax.swing.JTextArea textarea;
    public static javax.swing.JLabel username;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
